version: '3.0'
services:
  app:
    image: ghcr.io/h3poteto/yadockeri-base:202010031549
    working_dir: /go/src/github.com/h3poteto/yadockeri
    ports:
      - '9090:9090'
    volumes:
      - .:/go/src/github.com/h3poteto/yadockeri:cached
      - ~/.kube:/home/go/.kube
      - module:/go/pkg/mod
    environment:
      GO111MODULE: "on"
      ECHO_ENV: development
      CLIENT_ID: $GITHUB_CLIENT_ID
      CLIENT_SECRET: $GITHUB_CLIENT_SECRET
      SESSION_SECRET: $SESSION_SECRET
      ORGANIZATION: $ALLOW_GITHUB_ORG
      POSTGRES_HOST: db
      POSTGRES_USER: master
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: yadockeri
      KUBECONFIG: "/home/go/.kube/config"
    links:
      - db

  db:
    image: postgres:11.4-alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: master
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: yadockeri
    volumes:
      - storage:/var/lib/postgres/data

  frontend:
    image: node:12.7.0-alpine
    working_dir: /go/src/github.com/h3poteto/yadockeri
    volumes:
      - .:/go/src/github.com/h3poteto/yadockeri:cached
    entrypoint: sh -c
    command: |
      "yarn install &&
      yarn run build --watch"

volumes:
  storage:
  module:
